name: Keegan Lynch
personal_project: Weather-App
10-ux-ui-criticism:
- https://youtube.com/shorts/Gw_LBHSEaLI?feature=share
- https://youtube.com/shorts/K_TgmvWyPWM?feature=share
11-models-from-data:
- https://github.com/keeganlynch67/Weather-App

